SerialBuffer: cast to Buffer before calling position()
In Java 9, ByteBuffer got a position() method which returns a Buffer,
which is not compatible with Buffer.position().  This resulted in
crash:

 java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)